/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidacaoRouteImport } from './routes/validacao'
import { Route as RefloresteRouteImport } from './routes/refloreste'
import { Route as ProdutoresRouteImport } from './routes/produtores'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as IndexRouteImport } from './routes/index'

const ValidacaoRoute = ValidacaoRouteImport.update({
  id: '/validacao',
  path: '/validacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RefloresteRoute = RefloresteRouteImport.update({
  id: '/refloreste',
  path: '/refloreste',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoresRoute = ProdutoresRouteImport.update({
  id: '/produtores',
  path: '/produtores',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/chat': typeof ChatRoute
  '/creditos': typeof CreditosRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/mercado': typeof MercadoRoute
  '/perfil': typeof PerfilRoute
  '/produtores': typeof ProdutoresRoute
  '/refloreste': typeof RefloresteRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/chat': typeof ChatRoute
  '/creditos': typeof CreditosRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/mercado': typeof MercadoRoute
  '/perfil': typeof PerfilRoute
  '/produtores': typeof ProdutoresRoute
  '/refloreste': typeof RefloresteRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/chat': typeof ChatRoute
  '/creditos': typeof CreditosRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/mercado': typeof MercadoRoute
  '/perfil': typeof PerfilRoute
  '/produtores': typeof ProdutoresRoute
  '/refloreste': typeof RefloresteRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/chat'
    | '/creditos'
    | '/dashboard'
    | '/login'
    | '/mapa'
    | '/mercado'
    | '/perfil'
    | '/produtores'
    | '/refloreste'
    | '/validacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/chat'
    | '/creditos'
    | '/dashboard'
    | '/login'
    | '/mapa'
    | '/mercado'
    | '/perfil'
    | '/produtores'
    | '/refloreste'
    | '/validacao'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/chat'
    | '/creditos'
    | '/dashboard'
    | '/login'
    | '/mapa'
    | '/mercado'
    | '/perfil'
    | '/produtores'
    | '/refloreste'
    | '/validacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ChatRoute: typeof ChatRoute
  CreditosRoute: typeof CreditosRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MercadoRoute: typeof MercadoRoute
  PerfilRoute: typeof PerfilRoute
  ProdutoresRoute: typeof ProdutoresRoute
  RefloresteRoute: typeof RefloresteRoute
  ValidacaoRoute: typeof ValidacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validacao': {
      id: '/validacao'
      path: '/validacao'
      fullPath: '/validacao'
      preLoaderRoute: typeof ValidacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refloreste': {
      id: '/refloreste'
      path: '/refloreste'
      fullPath: '/refloreste'
      preLoaderRoute: typeof RefloresteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtores': {
      id: '/produtores'
      path: '/produtores'
      fullPath: '/produtores'
      preLoaderRoute: typeof ProdutoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  ChatRoute: ChatRoute,
  CreditosRoute: CreditosRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MercadoRoute: MercadoRoute,
  PerfilRoute: PerfilRoute,
  ProdutoresRoute: ProdutoresRoute,
  RefloresteRoute: RefloresteRoute,
  ValidacaoRoute: ValidacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
